// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0--rc1
// source: practice/practice.proto

package practice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Practice_GetName_FullMethodName = "/Practice/getName"
)

// PracticeClient is the client API for Practice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PracticeClient interface {
	GetName(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type practiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPracticeClient(cc grpc.ClientConnInterface) PracticeClient {
	return &practiceClient{cc}
}

func (c *practiceClient) GetName(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Practice_GetName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PracticeServer is the server API for Practice service.
// All implementations must embed UnimplementedPracticeServer
// for forward compatibility.
type PracticeServer interface {
	GetName(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPracticeServer()
}

// UnimplementedPracticeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPracticeServer struct{}

func (UnimplementedPracticeServer) GetName(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetName not implemented")
}
func (UnimplementedPracticeServer) mustEmbedUnimplementedPracticeServer() {}
func (UnimplementedPracticeServer) testEmbeddedByValue()                  {}

// UnsafePracticeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PracticeServer will
// result in compilation errors.
type UnsafePracticeServer interface {
	mustEmbedUnimplementedPracticeServer()
}

func RegisterPracticeServer(s grpc.ServiceRegistrar, srv PracticeServer) {
	// If the following call pancis, it indicates UnimplementedPracticeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Practice_ServiceDesc, srv)
}

func _Practice_GetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PracticeServer).GetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Practice_GetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PracticeServer).GetName(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Practice_ServiceDesc is the grpc.ServiceDesc for Practice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Practice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Practice",
	HandlerType: (*PracticeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getName",
			Handler:    _Practice_GetName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "practice/practice.proto",
}
